version: '3'
services:
  streamlit:
    build: .
    ports:
      - "8501:8501"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface